//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class LXFML
{

    private string buildingInstructionsField;

    private LXFMLMeta[] metaField;

    private LXFMLCamerasCamera[] camerasField;

    private LXFMLBricks[] bricksField;

    private LXFMLRigidSystemsRigidSystem[] rigidSystemsField;

    private LXFMLGroupSystemsGroupSystemGroup[][] groupSystemsField;

    private string versionMajorField;

    private string versionMinorField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BuildingInstructions
    {
        get
        {
            return this.buildingInstructionsField;
        }
        set
        {
            this.buildingInstructionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Meta", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLMeta[] Meta
    {
        get
        {
            return this.metaField;
        }
        set
        {
            this.metaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Camera", typeof(LXFMLCamerasCamera), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public LXFMLCamerasCamera[] Cameras
    {
        get
        {
            return this.camerasField;
        }
        set
        {
            this.camerasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Bricks", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLBricks[] Bricks
    {
        get
        {
            return this.bricksField;
        }
        set
        {
            this.bricksField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("RigidSystem", typeof(LXFMLRigidSystemsRigidSystem), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public LXFMLRigidSystemsRigidSystem[] RigidSystems
    {
        get
        {
            return this.rigidSystemsField;
        }
        set
        {
            this.rigidSystemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("GroupSystem", typeof(LXFMLGroupSystemsGroupSystemGroup[]), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Group", typeof(LXFMLGroupSystemsGroupSystemGroup), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false, NestingLevel = 1)]
    public LXFMLGroupSystemsGroupSystemGroup[][] GroupSystems
    {
        get
        {
            return this.groupSystemsField;
        }
        set
        {
            this.groupSystemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string versionMajor
    {
        get
        {
            return this.versionMajorField;
        }
        set
        {
            this.versionMajorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string versionMinor
    {
        get
        {
            return this.versionMinorField;
        }
        set
        {
            this.versionMinorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLMeta
{

    private LXFMLMetaApplication[] applicationField;

    private LXFMLMetaBrand[] brandField;

    private LXFMLMetaBrickSet[] brickSetField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Application", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLMetaApplication[] Application
    {
        get
        {
            return this.applicationField;
        }
        set
        {
            this.applicationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Brand", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLMetaBrand[] Brand
    {
        get
        {
            return this.brandField;
        }
        set
        {
            this.brandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BrickSet", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLMetaBrickSet[] BrickSet
    {
        get
        {
            return this.brickSetField;
        }
        set
        {
            this.brickSetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLMetaApplication
{

    private string nameField;

    private string versionMajorField;

    private string versionMinorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string versionMajor
    {
        get
        {
            return this.versionMajorField;
        }
        set
        {
            this.versionMajorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string versionMinor
    {
        get
        {
            return this.versionMinorField;
        }
        set
        {
            this.versionMinorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLMetaBrand
{

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLMetaBrickSet
{

    private string versionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLCamerasCamera
{

    private string refIDField;

    private string fieldOfViewField;

    private string distanceField;

    private string transformationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fieldOfView
    {
        get
        {
            return this.fieldOfViewField;
        }
        set
        {
            this.fieldOfViewField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distance
    {
        get
        {
            return this.distanceField;
        }
        set
        {
            this.distanceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transformation
    {
        get
        {
            return this.transformationField;
        }
        set
        {
            this.transformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLBricks
{

    private LXFMLBricksBrick[] brickField;

    private string cameraRefField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Brick", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLBricksBrick[] Brick
    {
        get
        {
            return this.brickField;
        }
        set
        {
            this.brickField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cameraRef
    {
        get
        {
            return this.cameraRefField;
        }
        set
        {
            this.cameraRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLBricksBrick
{

    private LXFMLBricksBrickPart[] partField;

    private string refIDField;

    private string designIDField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Part", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLBricksBrickPart[] Part
    {
        get
        {
            return this.partField;
        }
        set
        {
            this.partField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designID
    {
        get
        {
            return this.designIDField;
        }
        set
        {
            this.designIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLBricksBrickPart
{

    private LXFMLBricksBrickPartBone[] boneField;

    private string refIDField;

    private string designIDField;

    private string materialsField;

    private string decorationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Bone", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLBricksBrickPartBone[] Bone
    {
        get
        {
            return this.boneField;
        }
        set
        {
            this.boneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designID
    {
        get
        {
            return this.designIDField;
        }
        set
        {
            this.designIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string materials
    {
        get
        {
            return this.materialsField;
        }
        set
        {
            this.materialsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string decoration
    {
        get
        {
            return this.decorationField;
        }
        set
        {
            this.decorationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLBricksBrickPartBone
{

    private string refIDField;

    private string transformationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transformation
    {
        get
        {
            return this.transformationField;
        }
        set
        {
            this.transformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLRigidSystemsRigidSystem
{

    private LXFMLRigidSystemsRigidSystemRigid[] rigidField;

    private LXFMLRigidSystemsRigidSystemJoint[] jointField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rigid", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLRigidSystemsRigidSystemRigid[] Rigid
    {
        get
        {
            return this.rigidField;
        }
        set
        {
            this.rigidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Joint", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLRigidSystemsRigidSystemJoint[] Joint
    {
        get
        {
            return this.jointField;
        }
        set
        {
            this.jointField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLRigidSystemsRigidSystemRigid
{

    private string refIDField;

    private string transformationField;

    private string boneRefsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transformation
    {
        get
        {
            return this.transformationField;
        }
        set
        {
            this.transformationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string boneRefs
    {
        get
        {
            return this.boneRefsField;
        }
        set
        {
            this.boneRefsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLRigidSystemsRigidSystemJoint
{

    private LXFMLRigidSystemsRigidSystemJointRigidRef[] rigidRefField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RigidRef", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LXFMLRigidSystemsRigidSystemJointRigidRef[] RigidRef
    {
        get
        {
            return this.rigidRefField;
        }
        set
        {
            this.rigidRefField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLRigidSystemsRigidSystemJointRigidRef
{

    private string rigidRefField;

    private string aField;

    private string zField;

    private string tField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rigidRef
    {
        get
        {
            return this.rigidRefField;
        }
        set
        {
            this.rigidRefField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string a
    {
        get
        {
            return this.aField;
        }
        set
        {
            this.aField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string z
    {
        get
        {
            return this.zField;
        }
        set
        {
            this.zField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string t
    {
        get
        {
            return this.tField;
        }
        set
        {
            this.tField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LXFMLGroupSystemsGroupSystemGroup
{

    private string transformationField;

    private string pivotField;

    private string partRefsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transformation
    {
        get
        {
            return this.transformationField;
        }
        set
        {
            this.transformationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pivot
    {
        get
        {
            return this.pivotField;
        }
        set
        {
            this.pivotField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string partRefs
    {
        get
        {
            return this.partRefsField;
        }
        set
        {
            this.partRefsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private LXFML[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LXFML")]
    public LXFML[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
